services:
  - type: web
    name: crawl-data-prj
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    buildFilter:
      paths:
        - Dockerfile
        - ./**
